; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "RawBankEditor"
#define MyAppPublisher "iniss.6f.sk"
#define MyAppURL "https://iniss.6f.sk/"
#define MyAppExeName "RawBankEditor.exe"
#define MyAppDir SourcePath + "\RawBankEditor\bin\Release\net10.0-windows"
; Verzia sa číta zo zostaveného .exe, aby bola na jednom mieste - v Properties\AssemblyInfo.cs.
; Preto musí byť Release build hotový skôr, než sa inštalátor kompiluje (inak ISPP ohlási chybu).
#define MyAppVersion GetVersionNumbersString(MyAppDir + "\" + MyAppExeName)

[Setup]
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
; Predvolene sa instaluje iba pre aktualneho pouzivatela - do podpriecinka Programs v %LocalAppData%.
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputBaseFilename=rawbankeditor-setup
Compression=lzma
SolidCompression=yes
WizardStyle=modern
CreateUninstallRegKey=no
UpdateUninstallLogAppName=no
UsePreviousLanguage=no

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "czech"; MessagesFile: "compiler:Languages\Czech.isl"
Name: "slovak"; MessagesFile: "compiler:Languages\Slovak.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; config a logs vytvára program až za behu - s ignoreversion by aktualizácia prepísala nastavenia
Source: "{#MyAppDir}\*"; DestDir: "{app}"; Excludes: "\config,\logs"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[UninstallDelete]
; Nastavenia a logy si program zakladá až za behu, inštalátor o nich nevie a sám by ich nezmazal.
Type: filesandordirs; Name: "{localappdata}\{#MyAppName}"

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"
; Flags: nowait postinstall skipifsilent
