//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RawBankEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RawBankEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tento program slúži na úpravu binárnych súborov zvukovej banky, ktoré používa program INISS. 
        ///Program RawBankEditor nie je oficiálna aplikácia spoločnosti CHAPS ani spoločnosti INPROP..
        /// </summary>
        internal static string AboutAppDescription {
            get {
                return ResourceManager.GetString("AboutAppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ewa {
            get {
                object obj = ResourceManager.GetObject("ewa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naozaj si želáte previesť vybrané súbory/priečinky do formátu {0}?
        ///Tie zvuky, ktoré sú už v tomto formáte, ostanú zachované.
        ///
        ///Zadaná akcia môže trvať dlhšiu dobu..
        /// </summary>
        internal static string FMain_DoConvertFiles {
            get {
                return ResourceManager.GetString("FMain_DoConvertFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naozaj si želáte previesť všetky zvuky v skupine do formátu {0}?
        ///Tie zvuky, ktoré sú už v tomto formáte, ostanú zachované.
        ///
        ///Zadaná akcia môže trvať dlhšiu dobu..
        /// </summary>
        internal static string FMain_DoConvertGroup {
            get {
                return ResourceManager.GetString("FMain_DoConvertGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naozaj si želáte previesť všetky zvuky v jazyku do formátu {0}?
        ///Tie zvuky, ktoré sú už v tomto formáte, ostanú zachované.
        ///
        ///Zadaná akcia môže trvať dlhšiu dobu..
        /// </summary>
        internal static string FMain_DoConvertLang {
            get {
                return ResourceManager.GetString("FMain_DoConvertLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naozaj si želáte previesť vybrané zvuky do formátu {0}?
        ///Tie zvuky, ktoré sú už v tomto formáte, ostanú zachované.
        ///
        ///Zadaná akcia môže trvať dlhšiu dobu..
        /// </summary>
        internal static string FMain_DoConvertSounds {
            get {
                return ResourceManager.GetString("FMain_DoConvertSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niektoré zmeny sa už prejavili na disku.
        /// </summary>
        internal static string FMain_Disk_Changed_Discard {
            get {
                return ResourceManager.GetString("FMain_Disk_Changed_Discard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uloženie banky zlyhalo – súbory banky sa vrátili do pôvodného stavu.
        /// </summary>
        internal static string FMain_Save_Failed {
            get {
                return ResourceManager.GetString("FMain_Save_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uloženie banky zlyhalo a pôvodné súbory sa nepodarilo vrátiť.
        /// </summary>
        internal static string FMain_Save_Failed_Rollback {
            get {
                return ResourceManager.GetString("FMain_Save_Failed_Rollback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V súboroch ste vykonali zmeny. Uložiť zmeny?.
        /// </summary>
        internal static string FMain_Save_Changes {
            get {
                return ResourceManager.GetString("FMain_Save_Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap raw {
            get {
                object obj = ResourceManager.GetObject("raw", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba.
        /// </summary>
        internal static string RError {
            get {
                return ResourceManager.GetString("RError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informácia.
        /// </summary>
        internal static string RInfo {
            get {
                return ResourceManager.GetString("RInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otázka.
        /// </summary>
        internal static string RQuestion {
            get {
                return ResourceManager.GetString("RQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upozornenie.
        /// </summary>
        internal static string RWarning {
            get {
                return ResourceManager.GetString("RWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wav {
            get {
                object obj = ResourceManager.GetObject("wav", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otvoriť banku.
        /// </summary>
        internal static string Cmd_Open {
            get {
                return ResourceManager.GetString("Cmd_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložiť.
        /// </summary>
        internal static string Cmd_Save {
            get {
                return ResourceManager.GetString("Cmd_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uložiť všetko.
        /// </summary>
        internal static string Cmd_SaveAll {
            get {
                return ResourceManager.GetString("Cmd_SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Späť.
        /// </summary>
        internal static string Cmd_Undo {
            get {
                return ResourceManager.GetString("Cmd_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Znovu.
        /// </summary>
        internal static string Cmd_Redo {
            get {
                return ResourceManager.GetString("Cmd_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pridať zvuk.
        /// </summary>
        internal static string Cmd_AddSound {
            get {
                return ResourceManager.GetString("Cmd_AddSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odstrániť vybrané zvuky.
        /// </summary>
        internal static string Cmd_DeleteSounds {
            get {
                return ResourceManager.GetString("Cmd_DeleteSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premiestniť zvuky do inej skupiny.
        /// </summary>
        internal static string Cmd_MoveSounds {
            get {
                return ResourceManager.GetString("Cmd_MoveSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepisovací mód.
        /// </summary>
        internal static string Cmd_RewriteMode {
            get {
                return ResourceManager.GetString("Cmd_RewriteMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prispôsobiť text hlásenia v bunkách.
        /// </summary>
        internal static string Cmd_WrapTextSoundCol {
            get {
                return ResourceManager.GetString("Cmd_WrapTextSoundCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prejsť späť.
        /// </summary>
        internal static string Cmd_GoBack {
            get {
                return ResourceManager.GetString("Cmd_GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prejsť dopredu.
        /// </summary>
        internal static string Cmd_GoForward {
            get {
                return ResourceManager.GetString("Cmd_GoForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hľadať.
        /// </summary>
        internal static string Cmd_Search {
            get {
                return ResourceManager.GetString("Cmd_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pridať jazyk.
        /// </summary>
        internal static string Cmd_AddLanguage {
            get {
                return ResourceManager.GetString("Cmd_AddLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upraviť jazyk.
        /// </summary>
        internal static string Cmd_EditLanguage {
            get {
                return ResourceManager.GetString("Cmd_EditLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odstrániť jazyk.
        /// </summary>
        internal static string Cmd_DeleteLanguage {
            get {
                return ResourceManager.GetString("Cmd_DeleteLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastavenia programu.
        /// </summary>
        internal static string Cmd_AppSettings {
            get {
                return ResourceManager.GetString("Cmd_AppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zvýrazniť problém.
        /// </summary>
        internal static string Cmd_HighlightProblem {
            get {
                return ResourceManager.GetString("Cmd_HighlightProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyriešiť problém.
        /// </summary>
        internal static string Cmd_ResolveProblem {
            get {
                return ResourceManager.GetString("Cmd_ResolveProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte priečinok s INISS.exe.
        /// </summary>
        internal static string FMain_Vyberte_priecinok_s_INISS {
            get {
                return ResourceManager.GetString("FMain_Vyberte_priecinok_s_INISS", resourceCulture);
            }
        }
    }
}
